2025-03-06 15:56:22,525 - INFO - Processo iniciado pelo bot.
2025-03-06 15:56:54,714 - ERROR - Erro ao abrir site no navegador. HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB5E9F6F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:57:11,055 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB5F75E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:57:27,514 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB5E6B2F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:57:43,950 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB60485F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:58:00,214 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB6048E60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:58:16,554 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB5E6AA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:58:32,814 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB6048AA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:58:49,174 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB6048410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:59:05,674 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB6088230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 15:59:22,195 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=58857): Max retries exceeded with url: /session/54233d172136dc1f069380b7578a2b64/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB6088500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
