2025-03-06 16:00:05,282 - INFO - Processo iniciado pelo bot.
2025-03-06 16:00:10,698 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:00:35,425 - ERROR - Erro ao abrir site no navegador. HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A83E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:00:35,518 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:00:51,814 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192151E7050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:01:08,226 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A09B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:01:24,664 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A18B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:01:41,079 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A2120>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:01:57,374 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A1C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:02:13,694 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A1400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:02:30,013 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A0050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:02:46,458 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A1220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:03:02,911 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59021): Max retries exceeded with url: /session/f101535bbd60ffe513ec49226949261d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000192152A25D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:03:02,990 - INFO - Imagem capturada e salva no log do desenvolvedor.
