2025-03-06 16:06:37,708 - INFO - Processo iniciado pelo bot.
2025-03-06 16:06:43,027 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:07:04,159 - ERROR - Erro ao abrir site no navegador. HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235636983E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:07:04,227 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:07:20,595 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235635D7050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:07:37,045 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023563690B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:07:53,505 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235636918B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:08:09,875 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023563692120>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:08:26,205 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023563691C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:08:42,544 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023563691400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:08:58,818 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235636907D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:09:15,188 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023563691220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:09:31,540 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59220): Max retries exceeded with url: /session/8e943d0b0a2e038718d79d96a711d538/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235636925D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:09:31,609 - INFO - Imagem capturada e salva no log do desenvolvedor.
