2025-03-06 16:11:51,224 - INFO - Processo iniciado pelo bot.
2025-03-06 16:11:55,498 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:12:16,736 - ERROR - Erro ao abrir site no navegador. HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A82B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:12:16,809 - INFO - Imagem capturada e salva no log do desenvolvedor.
2025-03-06 16:12:33,130 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B456EB050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:12:49,526 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A0B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:13:05,935 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A18B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:13:22,164 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A2120>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:13:38,524 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A1C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:13:54,795 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A1400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:14:11,144 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A07D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:14:27,622 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A1220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:14:44,015 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=59454): Max retries exceeded with url: /session/e614a14e4603c6e73f342306e80f5725/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B457A25D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-06 16:14:44,083 - INFO - Imagem capturada e salva no log do desenvolvedor.
