2025-03-05 12:18:25,171 - INFO - Processo iniciado pelo bot.
2025-03-05 12:18:56,458 - ERROR - Erro ao preencher cotação dos correios: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-03-05 12:19:12,760 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E79917E9E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:19:29,116 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E799253950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:19:45,443 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7993308C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:20:01,781 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7993309B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:20:18,106 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E799330230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:20:34,385 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E799331130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:20:50,866 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E799370410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:21:07,296 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=63848): Max retries exceeded with url: /session/a3acc7142ce5620968fa1b0230606438/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E799370230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
