2025-03-05 12:27:24,466 - INFO - Processo iniciado pelo bot.
2025-03-05 12:27:57,745 - ERROR - Erro ao preencher cotação dos correios: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-03-05 12:28:14,086 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2DE8F230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:28:30,435 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2DF6B750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:28:46,816 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2E0548C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:29:03,131 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2E055130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:29:19,447 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2E0559A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:29:35,885 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2E058230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-05 12:29:52,296 - ERROR - Erro ao preencher cotação dos correios: HTTPConnectionPool(host='localhost', port=64076): Max retries exceeded with url: /session/afe1de3df85f20a0c4b8735fc6299452/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E2E058C80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
